# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 67e964e43eb5094fdf25781c6f910accc2300b9f2d35f514587a1c55be8df44d0337ddafcf4ea33be219c141fd0271d710c671edf284b03b4fe43c3a7e2148cb

test:
  secret_key_base: 1f2e3fd9501e4b797e61e44ac6a4bc2ff8eb1bfc5424b9e5318a7b541b4e3ce242408b110832ebd0d2bd47ed7eaba40604c362441170180bdf1f9ac6a4d15863

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
